'use strict';

const ICONS = {
  dashboard:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
  grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
  rocket:'<path d="M4.5 16.5c-1.5 1.3-2 4-2 4s2.7-.5 4-2m1-3-3-3 4-4C12 5 16.5 3.2 21 3c-.2 4.5-2 9-5.5 12.5l-4 4-3-3Zm4-4 3 3"/><circle cx="15" cy="9" r="1.5"/>',
  activity:'<path d="M3 12h4l3-8 4 16 3-8h4"/>',
  refresh:'<path d="M20 7v5h-5M4 17v-5h5"/><path d="M5.6 9A8 8 0 0 1 19 7l1 5M4 12l1 5a8 8 0 0 0 13.4-2"/>',
  cpu:'<rect x="6" y="6" width="12" height="12" rx="2"/><path d="M9 9h6v6H9zM9 2v4m6-4v4M9 18v4m6-4v4M2 9h4m-4 6h4m12-6h4m-4 6h4"/>',
  server:'<rect x="3" y="3" width="18" height="8" rx="2"/><rect x="3" y="13" width="18" height="8" rx="2"/><circle cx="7" cy="7" r=".8" fill="currentColor"/><circle cx="7" cy="17" r=".8" fill="currentColor"/>',
  harddrive:'<rect x="3" y="7" width="18" height="12" rx="2"/><path d="m6 7 3-4h6l3 4M7 15h.01M11 15h.01"/>',
  image:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m21 16-6-6L4 21"/>',
  wand:'<path d="m4 20 16-16M5 4v4M3 6h4m11 11v4m-2-2h4M12 2v3M10.5 3.5h3"/>',
  film:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M7 3v18M17 3v18M3 8h4m-4 8h4m10-8h4m-4 8h4"/>',
  music:'<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',
  box:'<path d="m12 2 9 5v10l-9 5-9-5V7l9-5Zm0 10 9-5m-9 5L3 7m9 5v10"/>',
  sparkles:'<path d="m12 3 1.6 5.4L19 10l-5.4 1.6L12 17l-1.6-5.4L5 10l5.4-1.6L12 3Zm7 14 .7 2.3L22 20l-2.3.7L19 23l-.7-2.3L16 20l2.3-.7L19 17ZM4 1l.7 2.3L7 4l-2.3.7L4 7l-.7-2.3L1 4l2.3-.7L4 1Z"/>',
  layers:'<path d="m12 2 9 5-9 5-9-5 9-5Zm-9 10 9 5 9-5M3 17l9 5 9-5"/>',
  check:'<path d="m5 12 4 4L19 6"/>',
  arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',
  shield:'<path d="m12 2 9 4v6c0 5-3.2 8-9 10-5.8-2-9-5-9-10V6l9-4Zm-4 10 3 3 5-6"/>',
  terminal:'<rect x="2" y="3" width="20" height="18" rx="2"/><path d="m6 8 4 4-4 4m6 0h5"/>',
  globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/>',
  alert:'<path d="m12 2 10 19H2L12 2Zm0 7v5m0 4h.01"/>',
  bolt:'<path d="m13 2-9 11h7l-1 9 10-12h-7V2Z"/>',
  chevron:'<path d="m9 18 6-6-6-6"/>',
  monitor:'<rect x="3" y="3" width="18" height="14" rx="2"/><path d="M8 21h8m-4-4v4"/>'
};
const icon = (name, size=18) => `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[name]||ICONS.layers}</svg>`;
const esc = value => String(value??'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={page:'overview',step:0,filter:'All',catalog:null,discovery:null,selected:new Set(['base','image']),mode:'new',llmUrl:'http://host.docker.internal:8001/v1',llmModel:'',comfyUrl:'http://host.docker.internal:8188',plan:null,job:null,jobs:[],busy:false,token:sessionStorage.getItem('cd-token')||''};
const stepLabels=['Environment','Components','Connections','Review','Deploy'];

async function api(path,body){
 const options={method:body===undefined?'GET':'POST',headers:{...(state.token?{'Authorization':'Bearer '+state.token}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{})}};
 if(body!==undefined)options.body=JSON.stringify(body);
 const res=await fetch('/api/'+path,options);
 if(res.status===401){const entered=window.prompt('This console requires its local access token. Enter COMFYDEPLOY_TOKEN:');if(entered){state.token=entered;sessionStorage.setItem('cd-token',entered);return api(path,body);}}
 let data;try{data=await res.json()}catch{throw Error('The server returned an invalid response')}
 if(!res.ok)throw Error(data.error||'Request failed');return data;
}
function toast(message,error=false){const region=document.getElementById('toast-region');const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;region.append(el);setTimeout(()=>el.remove(),4800)}
function putIcons(){document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon)})}
function setPage(page){state.page=page;if(page==='installer'&&state.step===4&&!state.job)state.step=0;render();window.scrollTo({top:0,behavior:'smooth'})}
function payload(extra={}){return {packs:[...state.selected],options:{reuse_backend:state.mode==='existing',install_backend:state.mode==='new',llm_url:state.llmUrl,llm_model:state.llmModel,comfy_url:state.comfyUrl},...extra}}
function badge(label,tone=''){return `<span class="status-chip ${tone}">${esc(label)}</span>`}
function cardStat(label,value,sub,ico){return `<div class="stat"><div class="stat-top">${esc(label)}<span class="stat-icon">${icon(ico)}</span></div><div class="stat-value">${esc(value)}</div><div class="stat-foot">${esc(sub)}</div></div>`}
function detailStatus(enabled){return enabled?badge('Detected'):badge('Not detected','off')}
function isReady(){return Boolean(state.discovery?.docker&&state.discovery?.compose)}
function numberText(n){return Number.isFinite(n)?n.toLocaleString(): '—'}

function overview(){const d=state.discovery;const found=d?.containers?.length||0;const gpu=d?.gpu?.[0];const ready=isReady();return `
 <div class="hero"><div class="hero-copy"><div class="eyebrow">YOUR CREATIVE INFRASTRUCTURE, SIMPLIFIED</div><h1>Build boldly.<br><span>Deploy beautifully.</span></h1><p>From first model to full production stack. Discover your environment, choose your capabilities, and let ComfyDeploy handle the heavy lifting.</p><div class="hero-buttons"><button class="btn btn-primary" data-page="installer">Start a deployment ${icon('arrow')}</button><button class="btn btn-outline" data-page="components">Explore components ${icon('grid')}</button></div></div><div class="hero-art" aria-hidden="true"><div class="art-ring"></div><div class="art-core"><svg viewBox="0 0 64 64" fill="none"><path d="M9 32 31 9l24 23-24 23Z" stroke="currentColor" stroke-width="3"/><circle cx="32" cy="32" r="9" fill="currentColor"/></svg></div><div class="art-mini m1"><span class="mini-ico">✦</span> Model orchestration</div><div class="art-mini m2"><span class="mini-ico">${icon('bolt',14)}</span> Zero guesswork</div></div></div>
 <div class="stats">${cardStat('DOCKER ENGINE',d?(d.docker?'Online':'Offline'):'Not scanned',d?.docker_version||'Container runtime', 'server')}${cardStat('GPU MEMORY',gpu?`${(gpu.vram_mb/1024).toFixed(1)} GB`:'—',gpu?.name||'No compatible GPU detected','cpu')}${cardStat('FREE DISK',d?`${d.disk_free_gb} GB`:'—','Deployment capacity','harddrive')}${cardStat('ACTIVE CONTAINERS',d?found:'—','Currently running', 'layers')}</div>
 <div class="section-heading"><div><h2>Infrastructure at a glance</h2><p>Real signals from the host, not simulated metrics.</p></div><button data-action="rescan">${icon('refresh',13)} &nbsp;Rescan system</button></div>
 <div class="two-column"><div class="panel"><div class="panel-head"><h3>Connected systems</h3>${d?badge(ready?'Docker ready':'Needs attention',ready?'':'warn'):badge('Scan required','off')}</div>
 ${systemRow('Docker engine',d?.docker,'Runtime for managed services','server')}${systemRow('NVIDIA GPU',Boolean(d?.gpu?.length),gpu?.name||'CUDA acceleration for image and video workloads','cpu')}${systemRow('ComfyUI endpoint',d?.endpoints?.comfyui?.online,'127.0.0.1:8188','image')}${systemRow('Local LLM endpoint',d?.endpoints?.llm?.online,'127.0.0.1:8001 — Unsloth / llama.cpp','bolt')}</div>
 <div class="panel scan-panel"><div class="panel-head"><h3>Deployment readiness</h3><span class="small-meta">SYSTEM CHECK</span></div><div class="device-illustration">${icon('monitor',72)}</div><div class="progress-track"><div class="progress-fill" style="width:${d?((Number(d.docker)+Number(d.compose)+Number(Boolean(gpu)))/3*100):0}%"></div></div><div class="scan-note">${!d?'Scan your host to see which components can be reused and what still needs to be installed.':ready?'Docker and Compose are available. Continue to the wizard to choose the installation strategy.':'Docker or Compose was not detected. Review your host prerequisites before attempting a deployment.'}</div><button class="btn btn-subtle" data-action="rescan">${icon('refresh')} ${d?'Scan again':'Scan this machine'}</button></div></div>
 <div class="section-heading"><div><h2>Quick-start capabilities</h2><p>Powerful tools, only a click away.</p></div><button data-page="components">View all components →</button></div>${packGrid((state.catalog?.packs||[]).filter(p=>p.id!=='base').slice(0,3))}`}
function systemRow(name,ok,subtitle,ico){return `<div class="system-row"><span class="system-symbol">${icon(ico)}</span><div><strong>${esc(name)}</strong><small>${esc(subtitle)}</small></div>${detailStatus(ok)}</div>`}
function packGrid(packs){return `<div class="pack-grid">${packs.map(p=>{const checked=state.selected.has(p.id);return `<button class="pack-card ${checked?'selected':''}" data-pack="${esc(p.id)}" aria-pressed="${checked}"><span class="pack-icon">${icon(p.icon||'layers')}</span><span class="pack-check">${icon('check',13)}</span><strong>${esc(p.name)}</strong><p>${esc(p.subtitle)}</p><span class="pack-tag">${p.default?'CORE':`${p.components.length} COMPONENTS`}</span></button>`}).join('')}</div>`}
function components(){const packs=state.catalog?.packs||[];const filters=['All','Core','Creation','Advanced'];const filtered=packs.filter(p=>state.filter==='All'||p.category===state.filter);return `<div class="title-bar"><div><div class="eyebrow">CURATED FOR YOUR HARDWARE</div><h1>Component library</h1><p>Mix and match. We resolve the dependencies and take care of the wiring.</p></div><button class="btn btn-primary" data-page="installer">Configure stack ${icon('arrow')}</button></div><div class="section-tabs">${filters.map(f=>`<button class="tab ${state.filter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div>${packGrid(filtered)}<div class="section-heading"><div><h2>How components work</h2><p>Each capability includes its own install manifest and dependency chain.</p></div></div><div class="two-column"><div class="panel"><div class="panel-head"><h3>Smart dependency resolution</h3>${badge('Automatic')}</div><p class="scan-note">Select a capability and ComfyDeploy plans the required model weights, ComfyUI backend, custom nodes and Studio integration. Existing files are detected and reusable assets are skipped.</p></div><div class="panel"><div class="panel-head"><h3>Controlled downloads</h3>${badge('Approval required','warn')}</div><p class="scan-note">Third-party model sources and licences are displayed before downloading. Downloads without recorded checksums require a separate approval; pin and verify assets before production use.</p></div></div>`}

function wizard(){const step=state.step;return `<div class="title-bar"><div><div class="eyebrow">THE INTELLIGENT DEPLOYMENT EXPERIENCE</div><h1>Deployment wizard</h1><p>Design your ideal stack. We'll map out what it takes.</p></div>${badge(`STEP ${step+1} OF 5`)}</div><div class="wizard-steps">${stepLabels.map((s,i)=>`<button class="wizard-step ${i===step?'active':i<step?'done':''}" data-step="${i}"><span class="step-number">${i<step?icon('check',12):i+1}</span>${esc(s)}</button>`).join('')}</div><div class="wizard-grid"><div class="wizard-body"><div class="wizard-card">${wizardStep(step)}<div class="wizard-footer"><button class="btn btn-subtle" data-action="back" ${step===0?'disabled':''}>← Back</button>${step<3?`<button class="btn btn-primary" data-action="next">Continue ${icon('arrow')}</button>`:step===3?`<button class="btn btn-primary" data-action="open-confirm" ${!state.plan?'disabled':''}>Deploy this stack ${icon('rocket')}</button>`:`<button class="btn btn-subtle" data-page="activity">View activity ${icon('arrow')}</button>`}</div></div></div><aside class="aside-sticky"><div class="panel"><div class="summary-head"><h3>Stack summary</h3><span class="summary-pill">${state.selected.size} packs</span></div><div class="summary-row"><span>Components selected</span><strong>${countComponents()}</strong></div><div class="summary-row"><span>Deployment mode</span><strong>${state.mode==='new'?'Managed stack':'Connect existing'}</strong></div><div class="summary-row"><span>LLM provider</span><strong>OpenAI compatible</strong></div><div class="summary-row"><span>Model downloads</span><strong>${state.plan?.steps.filter(s=>s.type==='model').length??'To be planned'}</strong></div><div class="summary-row"><span>Install directory</span><strong>~/.comfydeploy</strong></div><hr class="divider"><div class="notice">${icon('shield',17)} &nbsp; No changes are made until you approve and begin deployment.</div></div></aside></div>`}
function countComponents(){const catalog=state.catalog?.components||{};const ids=new Set();for(const p of state.catalog?.packs||[])if(state.selected.has(p.id))for(const c of p.components)ids.add(c);return Object.keys(catalog).length?ids.size:'—'}
function wizardStep(n){if(n===0)return `<div class="eyebrow">01 / SET YOUR FOUNDATION</div><h2>Where are we deploying?</h2><p class="subcopy">Choose whether ComfyDeploy manages a new ComfyUI backend or connects to the one you already have.</p><div class="choice-list"><button class="choice ${state.mode==='new'?'selected':''}" data-mode="new"><i></i><span><strong>Deploy a complete managed stack</strong><small>Install ComfyUI, Studio and selected model packs from scratch.</small></span><span class="right-tag">RECOMMENDED</span></button><button class="choice ${state.mode==='existing'?'selected':''}" data-mode="existing"><i></i><span><strong>Use my existing ComfyUI instance</strong><small>Connect to an existing backend, generate Studio config, download model files separately.</small></span></button></div><hr class="divider"><div class="notice">${icon('server',17)} &nbsp; ${isReady()?'Docker and Compose detected on this host.':'Docker/Compose not yet confirmed. Run environment discovery before deploying.'}</div>`;
 if(n===1)return `<div class="eyebrow">02 / UNLOCK YOUR TOOLKIT</div><h2>Choose your superpowers.</h2><p class="subcopy">Pick any combination. Dependent components are automatically included in the installation plan.</p>${packGrid(state.catalog?.packs||[])}`;
 if(n===2)return `<div class="eyebrow">03 / CONNECT THE DOTS</div><h2>Make everything talk.</h2><p class="subcopy">Wire ComfyUI Studio to your local Unsloth/Qwen endpoint and ComfyUI backend. These addresses must be reachable from inside the Studio container.</p><div class="field"><label class="form-label" for="llm-url">OPENAI-COMPATIBLE LLM BASE URL</label><input id="llm-url" class="form-control" value="${esc(state.llmUrl)}" placeholder="http://host.docker.internal:8001/v1"/><small class="field-note">Unsloth / llama.cpp commonly exposes an OpenAI-compatible /v1 endpoint.</small></div><div class="field"><label class="form-label" for="llm-model">MODEL ID / ALIAS</label><input id="llm-model" class="form-control" value="${esc(state.llmModel)}" placeholder="Auto-select in Studio if left blank"/></div><div class="field"><label class="form-label" for="comfy-url">EXTERNAL COMFYUI URL</label><input id="comfy-url" class="form-control" value="${esc(state.comfyUrl)}" ${state.mode==='new'?'disabled':''}/><small class="field-note">${state.mode==='new'?'Managed deployment uses the internal Docker service name automatically.':'For external backends, use a hostname reachable from inside Studio.'}</small></div>`;
 if(n===3)return `<div class="eyebrow">04 / BEFORE TAKEOFF</div><h2>Review your flight plan.</h2><p class="subcopy">This is a preview only. Check dependencies, warnings and sources before approving changes.</p>${state.plan?planPreview():`<div class="empty"><div class="empty-icon">${icon('activity',32)}</div><h3>Building your plan</h3><p>Reading component dependencies and available assets.</p></div>`}`;
 return `<div class="eyebrow">05 / DEPLOYMENT CENTRE</div><h2>${state.job?.status==='complete'?'Your stack is ready.':state.job?.status==='failed'?'Deployment needs attention.':'Making the magic happen.'}</h2><p class="subcopy">Live step-by-step updates from your local deployment agent.</p>${jobPreview()}`;
}
function planPreview(){const p=state.plan;return `<div class="plan-table"><div class="plan-row header"><span>Component</span><span>Action</span><span>Integrity</span></div>${p.steps.map(s=>`<div class="plan-row"><strong>${esc(s.name)}</strong><span>${esc(s.cached?'Cached':s.action)}</span><span>${s.unverified?'<span style="color:var(--orange)">Unverified</span>':esc(s.type==='model'?'Verified':'Source')}</span></div>`).join('')}</div>${p.warnings.length?`<div style="margin-top:17px" class="warning-box">${icon('alert')}<div>${p.warnings.slice(0,5).map(w=>`<div>• ${esc(w)}</div>`).join('')}</div></div>`:'<div style="margin-top:15px" class="notice">All known plan checks passed.</div>'}<p class="field-note" style="margin-top:15px">${p.steps.length} ordered actions · Root: ${esc(p.root)}</p>`}
function jobPreview(){const job=state.job;if(!job)return `<div class="empty"><h3>Not deployed yet</h3><p>Review the plan and approve your installation to start.</p></div>`;const events=job.events||[];return `<div style="margin-bottom:17px">${badge(job.status.toUpperCase(),job.status==='failed'?'warn':'')}</div><div class="terminal" id="terminal">${events.map(ev=>`<div><span class="stamp">${new Date(ev.time*1000).toLocaleTimeString()} </span>${ev.kind==='error'?'<span class="bad">ERROR </span>':ev.ok===true?'<em>✓ </em>':''}${esc(ev.message||ev.status||ev.file||ev.component||ev.kind)}${ev.bytes?' — '+(ev.bytes/1048576).toFixed(0)+' MB':''}</div>`).join('')||'<em>Preparing deployment…</em>'}</div>${job.report?`<p class="field-note">${job.report.success?'Installation steps completed.':'One or more steps failed.'} Full report: ${esc(job.report.root)}/last-report.json</p>`:''}`}
function activity(){return `<div class="title-bar"><div><div class="eyebrow">FULL VISIBILITY</div><h1>Activity & logs</h1><p>A clear audit trail of recent deployment actions in this console session.</p></div><button class="btn btn-subtle" data-action="refresh-jobs">${icon('refresh')} Refresh</button></div>${state.jobs.length?`<div class="activity-list">${state.jobs.map(j=>`<button class="activity-item" data-job="${esc(j.id)}"><div><strong>Deployment ${esc(j.id)}</strong><small>${new Date(j.created_at*1000).toLocaleString()} · ${(j.events||[]).length} recorded events</small></div>${badge(j.status.toUpperCase(),j.status==='failed'?'warn':'')}</button>`).join('')}</div>`:`<div class="empty"><div class="empty-icon">${icon('terminal',34)}</div><h3>No deployment activity yet</h3><p>Once you install a stack, its live status and results will appear here.</p><button class="btn btn-primary" data-page="installer">Create your first deployment ${icon('arrow')}</button></div>`}`}
function render(){const labels={overview:'Overview',components:'Component library',installer:'Deployment wizard',activity:'Activity & logs'};document.getElementById('breadcrumb').textContent=labels[state.page];document.querySelectorAll('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.page===state.page));document.getElementById('sidebar-pack-count').textContent=state.catalog?.packs?.length||0;const d=state.discovery;document.getElementById('sidebar-status').innerHTML=`<span class="live-dot ${!d?'muted':isReady()?'':'warn'}"></span>${!d?'Environment not scanned':isReady()?'Docker runtime ready':'Runtime needs attention'}`;document.getElementById('top-dot').className='live-dot '+(!d?'muted':isReady()?'':'warn');document.getElementById('env-label').textContent=!d?'Awaiting scan':isReady()?'Host connected':'Check prerequisites';document.getElementById('view').innerHTML=state.page==='overview'?overview():state.page==='components'?components():state.page==='installer'?wizard():activity();putIcons();const term=document.getElementById('terminal');if(term)term.scrollTop=term.scrollHeight}
async function scan(){try{document.getElementById('refresh-button').disabled=true;const d=await api('discover');state.discovery=d;render();toast('Environment discovery complete.')}catch(e){toast(e.message,true)}finally{document.getElementById('refresh-button').disabled=false}}
async function buildPlan(){try{state.plan=null;render();state.plan=await api('plan',payload());render()}catch(e){toast(e.message,true)}}
async function startInstall(){try{const value=await api('apply',payload({approve:true,allow_unverified:document.getElementById('confirm-unverified').checked,start:document.getElementById('confirm-start').checked}));document.getElementById('confirm-modal').classList.add('hidden');state.step=4;state.job={id:value.job_id,status:'running',events:[]};render();await refreshJob();toast('Deployment started. Follow live progress in the console.')}catch(e){toast(e.message,true)}}
async function refreshJob(){if(!state.job||!state.job.id)return;try{state.job=await api('jobs/'+state.job.id);if(state.page==='installer'&&state.step===4)render();if(state.job.status!=='running')await refreshJobs()}catch(e){console.error(e)}}
async function refreshJobs(){try{const d=await api('jobs');state.jobs=d.jobs||[];if(state.page==='activity')render()}catch(e){toast(e.message,true)}}
function togglePack(id){if(id==='base')return toast('Studio Core is always included.');if(state.selected.has(id))state.selected.delete(id);else state.selected.add(id);state.plan=null;render()}
function readInputs(){const l=document.getElementById('llm-url');const m=document.getElementById('llm-model');const c=document.getElementById('comfy-url');if(l)state.llmUrl=l.value.trim();if(m)state.llmModel=m.value.trim();if(c)state.comfyUrl=c.value.trim()}
function validateConnections(){for(const input of [state.llmUrl,...(state.mode==='existing'?[state.comfyUrl]:[])]){try{const url=new URL(input);if(!['http:','https:'].includes(url.protocol))throw Error('protocol')}catch{toast('Enter a valid HTTP(S) endpoint URL.',true);return false}}return true}
function showModal(){document.getElementById('confirm-modal').classList.remove('hidden');document.getElementById('confirm-agree').checked=false;document.getElementById('confirm-unverified').checked=false;document.getElementById('approve-install').disabled=true}
function handleClick(e){const target=e.target.closest('button');if(!target)return;if(target.dataset.page){setPage(target.dataset.page);return}if(target.dataset.pack){togglePack(target.dataset.pack);return}if(target.dataset.filter){state.filter=target.dataset.filter;render();return}if(target.dataset.mode){state.mode=target.dataset.mode;state.plan=null;render();return}if(target.dataset.step!==undefined){readInputs();const requested=Number(target.dataset.step);if(requested>=3){if(!validateConnections())return;state.step=requested;buildPlan()}else{state.step=requested;render()}return}if(target.dataset.job){state.job=state.jobs.find(j=>j.id===target.dataset.job);state.step=4;setPage('installer');return}const action=target.dataset.action;if(action==='rescan'){scan();return}if(action==='refresh-jobs'){refreshJobs();return}if(action==='back'){state.step=Math.max(0,state.step-1);render();return}if(action==='next'){readInputs();if(state.step===2&&!validateConnections())return;state.step=Math.min(4,state.step+1);if(state.step===3)buildPlan();else render();return}if(action==='open-confirm'){showModal();return}}
async function init(){document.addEventListener('click',handleClick);document.getElementById('refresh-button').addEventListener('click',scan);document.getElementById('cancel-install').addEventListener('click',()=>document.getElementById('confirm-modal').classList.add('hidden'));document.getElementById('confirm-agree').addEventListener('change',e=>document.getElementById('approve-install').disabled=!e.target.checked);document.getElementById('approve-install').addEventListener('click',startInstall);document.getElementById('confirm-modal').addEventListener('click',e=>{if(e.target.id==='confirm-modal')e.target.classList.add('hidden')});try{state.catalog=await api('catalog');render();const jobs=await api('jobs');state.jobs=jobs.jobs||[];await scan()}catch(e){toast(e.message,true);render()}setInterval(()=>{if(state.job?.status==='running')refreshJob()},1700)}
init();
